params:
  # parameters for the FDL component
  FDL:
    term_dictionary: icd/bsv_icd_syn.bsv
    term_scheme: CUI|TUI|TTY|CODE|SAB|STR|PREF
    concept_dictionary: icd/bsv_icd_syn.bsv
    concept_scheme: CUI|TUI|TTY|CODE|SAB|STR|PREF
    concept_params_ignore: [STR]
    exclusion_tags: [VB]
    precision_mode: True

pipeline: default_clinical

features:
  - polarity

