request_params:
  lookup_mode: code
params:
  # parameters for the FDL component
  FDL:
    term_dictionary: icd10/ICD10.bsv
    term_scheme: CUI|TUI|TTY|STR|SAB|TXT|PREF
    concept_dictionary: icd10/ICD10.bsv
    concept_scheme: CUI|TUI|TTY|CODE|SAB|STR|PREF
    concept_params_ignore: [STR]
    exclusion_tags: [VB]
    precision_mode: True

pipeline: default_clinical

features:
  - polarity

