params:
  # parameters for the FDL component
  FDL:
    term_dictionary: rxnorm/bsv_drug.bsv
    term_scheme: CUI|TUI|TTY|CODE|SAB|STR|PREF
    concept_dictionary: rxnorm/bsv_drug.bsv
    concept_scheme: CUI|TUI|TTY|CODE|SAB|STR|PREF
    concept_params_ignore: [STR]
    exclusion_tags: [VB]
    precision_mode: True

pipeline: default_clinical

features:
  - drug
  - polarity